import mongoose from "mongoose"
const EmployeeSchema=new mongoose.Schema(
    {
        name:
        {
            type:String,
            required:true,
            unique:true
        },
        email:
        {
            type:String,
            required:true,
            unique:true
        },
        password:
        {
            type:String
        },
        phone:
        {
            type:Number
        },summary:
        {
            type:String
        },address:
        {
            type:String
        },country:
        {
            type:String
        },
        jobsAppliedFor:
        {
            type:[String],
            default:[]
        },
        resumeURL:
        {
            type:String,
            default:""
        },
        viewedJobs:
        {
            type:[String],
            default:[]
        },isEmployer:
        {
            type:Boolean,
            default:false
        },
        resetToken:String,
        expireToken:Date
    },{timestamps:true})
    export default mongoose.model("Employees",EmployeeSchema)